### ISSUE TITLE
Trying to use this in a global package but having issues with permissions

### ISSUE THREAD

**Issue by CrashyBang** [tschaub/gh-pages#118]
I have the following script, which I have installed globally:

```js
#!/usr/bin/env node

const path = require('path');
const yargs = require('yargs').argv;
const ghpages = require('gh-pages');

ghpages.publish(path.join(process.cwd(), './dist'), {
  branch: 'master'
}, err => {
  console.log(err, process.cwd());
});
```

I am getting the following error:

```
{ ProcessError: fatal: could not create work tree dir '../../../../usr/lib/node_modules/gh-deploy-extended/node_modules/gh-pages/.cache': Permission denied

    at ChildProcess.<anonymous> (/usr/lib/node_modules/gh-deploy-extended/node_modules/gh-pages/lib/git.js:47:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
  code: 128,
  message: 'fatal: could not create work tree dir \'../../../../usr/lib/node_modules/gh-deploy-extended/node_modules/gh-pages/.cache\': Permission denied\n',
  name: 'ProcessError' } '/home/otis/Developer/portfolio'
```

If I add the following option: `clone: '/tmp/gh-pages'` I stop getting permission errors and get the following:

```
{ Error: ENOENT: no such file or directory, mkdir ''
    at Error (native) errno: -2, code: 'ENOENT', syscall: 'mkdir', path: '' } '/home/otis/Developer/portfolio'
``` 

Any ideas?
Cheers.

**Comment by nkbt** [comment]
The problem is in the library code. I have the same issue.

If you use absolute path, then:

in this function
```js
var uniqueDirs = exports.uniqueDirs = function(files) {
  var dirs = {};
  files.forEach(function(filepath) {
    var parts = path.dirname(filepath).split(path.sep);
    var partial = parts[0]; // <--- this is empty.
    dirs[partial] = true;
    for (var i = 1, ii = parts.length; i < ii; ++i) {
      partial = path.join(partial, parts[i]);
      dirs[partial] = true;
    }
  });
  return Object.keys(dirs);
};
```

So later:
```js
dirsToCreate(destFiles) [ '', 'tmp', 'tmp/react-interval' ]
```

And then  `fs.mkdir('')` fails. 

I reckon it would make sense to use `mkdirp` instead of this custom implementation. Or, well, fix the issue...

**Comment by nkbt** [comment]
Quick hacky fix is to use `path.relative` like:

```js
  clone: path.relative(process.cwd(), '/tmp/react-interval')
```

That results in something like

```js
dirsToCreate(destFiles) [ '..',
  '../..',
  '../../..',
  '../../../..',
  '../../../../..',
  '../../../../../..',
  '../../../../../../tmp',
  '../../../../../../tmp/react-interval' ]
```

And then works just fine.

**Comment by nkbt** [comment]
Apparently fixed by https://github.com/tschaub/gh-pages/pull/85
