### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by ccorcos** [tschaub/gh-pages#151]
I'm trying to debug why this happens, but the stack trace doesnt appear to be very useful

```
Cloning /root/doug-app-origin into ../doug/packages/doug/node_modules/gh-pages/.cache
Cleaning
Fetching origin
Checking out origin/gh-pages
Removing files
Copying files
Adding all
Committing
Pushing
Error
    at ChildProcess.<anonymous> (/root/doug/packages/doug/node_modules/gh-pages/lib/git.js:47:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
(node:310) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: true
(node:310) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ccorcos** [comment]
This could have to do with running Node 7 since there are build-in Promises
