### ISSUE TITLE
Error running example script 

### ISSUE THREAD

**Issue by wagenaartje** [tschaub/gh-pages#195]
I have a simple script set up:

```js
var ghpages = require('gh-pages');
var path = require('path');

ghpages.publish('dist', function (error) {
  console.log(error)
});
```

It throws this error everytime I run it:

```cmd
{ Error
    at ChildProcess.<anonymous> (C:\Users\THOMAS\Documents\GitHub\neataptic\node_modules\gh-pages\lib\git.js:42:16)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:897:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
  code: 128,
  message: 'github --credentials get: github: command not found\nbash: /dev/tty: No such device or address\nerror: failed to execute prompt script (exit code 1)\nfatal: could not read Username for \'https://github.com\': Invalid argument\n',
  name: 'ProcessError' }
```

OS: Windows 10

**Comment by nikolaysalinder** [comment]
I have the same problem for repo github.com/nikolaysalinder/barbershop

**Comment by cpilson** [comment]
My configuration just broke also. It was working nine days ago, but is now broken. I did run an update on gatsby-netlify-cms, but I'm not sure if/how this would interact with the gh-pages package.

I did a "dummy push" in the CLI to authenticate with my username and password with GitHub, but I still receive this message. 

> fatal: HttpRequestException encountered.
>   An error occurred while sending the request.
> bash: /dev/tty: No such device or address
> error: failed to execute prompt script (exit code 1)
> fatal: could not read Username for 'https://github.com': No error

I haven't changed ssl keys or the like on this end. 

> git config -l

 doesn't have a Username object.
