### ISSUE TITLE
Can it support CI?

### ISSUE THREAD

**Issue by 951565664** [tschaub/gh-pages#306]
Can it support CI? 

```bash
Error: spawn git ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
```

**Comment by swatityagi23** [comment]
I am also getting this error. Please help.
