### ISSUE TITLE
throw new TypeError (Path must be a string) 

### ISSUE THREAD

**Issue by chaoren1641** [tschaub/gh-pages#45]
this is my publish commond in npm scripts:
```sh
"scripts": {
    "deploy": "gh-pages -b demo -s {docs/**/*,build/**/*,index.html}",
},
```

when I run it, it's going to be wrong.throw an exception

```sh
path.js:8
    throw new TypeError('Path must be a string. Received ' +
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.posix.join (path.js:479:5)
    at Object.<anonymous> (/Users/chenchaoqun/GitLab/aliqin/vue-component/node_modules/gh-pages/bin/gh-pages:23:22)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3
```

when I use the nodejs code to run, it will not be reported to the wrong, how to solve this problem?

**Comment by mesupp** [comment]
jeah sorry man had some problems with my ifrastructre of my pc.... bit new with git so  din't expect it would go pul so hard... . i was working  on my other pc so i promise no more win stuf

**Comment by kisonic** [comment]
You forgot `-d` parameter and quotes
```json
"scripts": {
    "deploy": "gh-pages -b demo -d . -s '{docs/**/*,build/**/*,index.html}'"
}
```
