### ISSUE TITLE
Error: spawn ENAMETOOLONG

### ISSUE THREAD

**Issue by Krinopotam** [tschaub/gh-pages#585]
After updating to version 6.2.0, when I call the `gh-pages --nojekyll -d deploy` command, I get the following error: 
```
Error: spawn ENAMETOOLONG
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at Object.spawn (node:child_process:761:9)
    at d:\projects\@krinopotam\ui-kit\node_modules\gh-pages\lib\git.js:30:22
    at new Promise (<anonymous>)
    at spawn (d:\projects\@krinopotam\ui-kit\node_modules\gh-pages\lib\git.js:29:10)
    at Git.exec (d:\projects\@krinopotam\ui-kit\node_modules\gh-pages\lib\git.js:69:10)
    at Git.rm (d:\projects\@krinopotam\ui-kit\node_modules\gh-pages\lib\git.js:146:15)
    at d:\projects\@krinopotam\ui-kit\node_modules\gh-pages\lib\index.js:180:22
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by darainfo** [comment]
It seems to be an error occurring on Windows.
I have temporarily resolved it by modifying the file as follows:

By replacing the Git.prototype.rm section in the node_modules\gh-pages\lib\git.js file with the code below, the issue is resolved.


```
const os = require('os');
/**
 * Remove all unversioned files.
 * @param {string | Array<string>} files Files argument.
 * @return {Promise} A promise.
 */
Git.prototype.rm = function (files) {
  if (!Array.isArray(files)) {
    files = [files];
  }

  if(os.platform() ==='win32'){
    return separateRm(this, files);
  } else{
    return this.exec('rm', '--ignore-unmatch', '-r', '-f', ...files);
  }
};

/**
 * files separate deletion
 * 
 * @param {Git} thisObj git
 * @param {Array} files files Files argument
 * @returns 
 */
async function separateRm (thisObj , files ) {

  const limitFileCount = 100;
  const fileLength = files.length;
  let loopCount = Math.ceil(fileLength /limitFileCount);

  let startIdx = 0;
  const allExecResult =[];
  let endIdx =limitFileCount; 
  for(let i =0;i <loopCount; i++){

    if(endIdx > fileLength){
      endIdx = fileLength-1;
    }

    let rmFiles = files.slice(startIdx, endIdx);
    allExecResult.push(await thisObj.exec('rm', '--ignore-unmatch', '-r', '-f', ...rmFiles));
    startIdx  = endIdx;
    endIdx = endIdx+ limitFileCount;
  }

  return allExecResult[allExecResult.length-1];
}
```

**Comment by verveguy** [comment]
Here's a patch for 6.3.0 that simplifies the rm to simply remove `.` rather that futzing with all the files. 

Seems to work for my case...YMMV.

```patch
diff --git a/lib/git.js b/lib/git.js
index d4c5724272d00bd1f0d76c47dab47d21ccd094d9..d86ac2b0bd7cbc02f34a50dac6980965102ee964 100644
--- a/lib/git.js
+++ b/lib/git.js
@@ -143,7 +143,7 @@ Git.prototype.rm = function (files) {
   if (!Array.isArray(files)) {
     files = [files];
   }
-  return this.exec('rm', '--ignore-unmatch', '-r', '-f', '--', ...files);
+  return this.exec('rm', '--ignore-unmatch', '-r', '-f', '--', '.');
 };
 
 /**
```

I'm using pnpm, so I put the above in `patches/gh-pages.patch` and then this works:

```json
"pnpm": {
    "patchedDependencies": {
      "gh-pages": "patches/gh-pages.patch"
    }
  }
```

**Comment by CallusCEO** [comment]
> Here's a patch for 6.3.0 that simplifies the rm to simply remove `.` rather that futzing with all the files.
> 
> Seems to work for my case...YMMV.
> 
> diff --git a/lib/git.js b/lib/git.js
> index d4c5724272d00bd1f0d76c47dab47d21ccd094d9..d86ac2b0bd7cbc02f34a50dac6980965102ee964 100644
> --- a/lib/git.js
> +++ b/lib/git.js
> @@ -143,7 +143,7 @@ Git.prototype.rm = function (files) {
>    if (!Array.isArray(files)) {
>      files = [files];
>    }
> -  return this.exec('rm', '--ignore-unmatch', '-r', '-f', '--', ...files);
> +  return this.exec('rm', '--ignore-unmatch', '-r', '-f', '--', '.');
>  };
>  
>  /**
> I'm using pnpm, so I put the above in `patches/gh-pages.patch` and then this works:
> 
> "pnpm": {
>     "patchedDependencies": {
>       "gh-pages": "patches/gh-pages.patch"
>     }
>   }

The GOAT

**Comment by edgalvin88** [comment]
I had this same issue on a docusauras build in the past few days. I didn't feel comfortable applying the above workaround as it was on a shared built agent where some builds were succeeding and others (mine of course!) failing. 

I pinned the version of gh-pages to 6.1.0 in the end - found that 6.2.x exhibited the same behaviour if that helps at all in tracking down the issue.

**Comment by Fefer-Ivan** [comment]
I had similar issue on mac os x with Error: spawn E2BIG

**Comment by Prozilla** [comment]
This issue is still occurring on version 6.3.0. Is there a fix yet?

**Comment by hakimio** [comment]
@Prozilla the fix: https://github.com/hakimio/ngx-ui-tour/blob/master/patches/gh-pages%406.3.0.patch

**Comment by Prozilla** [comment]
> [@Prozilla](https://github.com/Prozilla) the fix: https://github.com/hakimio/ngx-ui-tour/blob/master/patches/gh-pages%406.3.0.patch

If that is the fix, why was that not included in the PR?

**Comment by hakimio** [comment]
Maybe you should ask @tschaub ?
